### ISSUE TITLE
[BUG] Strange behaviour when rescheduling cards

### ISSUE THREAD

**Issue by johtso** [open-spaced-repetition/fsrs4anki-helper#116]
I've just noticed some odd behaviour when rescheduling my cards.

I have load balancing enabled and auto reschedule on sync.

My schedular code got replaced after an ankidroid sync (as it always does open-spaced-repetition/fsrs4anki#192), so I edited the options to correct the schedular and then did a reschedule from the deck menu.

I was expecting to have 0 reviews due, but for some reason it showed 15 or so.

I then pressed sync and it went down to 1 review due (I'm guessing the sync applied the load balancing when the menu action didn't?).

I then rescheduled from the deck menu again and the due count went down to 0 (!).

Any idea what's going on there? What is the behaviour supposed to be?

**Comment by L-M-Sherlock** [comment]
Should we allow FSRS to reschedule cards to the past when  load balance is enabled? If we ban it, this issue could be solved.

**Comment by jowls** [comment]
Sorry I disabled load balance/days off to avoid this issue back in April so can't comment on whether it still exists. My review habits have changed a bit so I'm not sure if I could reproduce it now to test the fix with my current deck/history.

What are you thinking would be done with the cards that would previously have been scheduled into past dates? Scheduled for current day?

I think the thing to test would be: if reschedule adds cards to the current day because of low repetitions on past dates, and then all of those are then reviewed down to 0 on that day, any subsequent reschedules performed on the same day doesn't continue to add large batches of reviews each time the reschedule is run. I can understand with fuzzing you might get a small number that change, but it felt like what I was seeing was cards continually being rescheduled into the past with no trend towards stability in the rescheduling as I kept performing all of the additional reviews it was asking.

**Comment by L-M-Sherlock** [comment]
> What are you thinking would be done with the cards that would previously have been scheduled into past dates? Scheduled for current day?

I don't use this feature. Maybe we need to ask other users.

**Comment by L-M-Sherlock** [comment]
OK. We need to add limit for load balance. If the card is undue, load balance shouldn't reschedule it to due or overdue.

**Comment by perhydrol** [comment]
I have install the latest helper. It works. 
![Snipaste_2023-08-13_14-43-42](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/50535400/3a1bb13e-28d1-4092-aa8d-685b9330acde)
![Snipaste_2023-08-13_14-43-04](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/50535400/e2c59882-da42-4663-a8a7-f8ae87c084b5)
I seem to have misunderstood in https://github.com/open-spaced-repetition/fsrs4anki/issues/382 that the load balancing is done by different decks that I divide in the js file.
So, load balancing is performed on collections, right?

**Comment by L-M-Sherlock** [comment]
> So, load balancing is performed on collections, right?

Yeah. Load balance is global.

**Comment by L-M-Sherlock** [comment]
OK. I will merge the branch.
