### ISSUE TITLE
Review interval issues

### ISSUE THREAD

**Issue by propofolpapi** [open-spaced-repetition/fsrs4anki-helper#140]
Hello, stumbled upon fsrs a few months ago and started using it more often. I'll get an occasional card that starts off in ease hell or reverts to an early interval automatically similar to the picture below. Is this an issue with the parameters or is the optimizer working as intended? Thanks

<img width="771" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/136776048/70e4e600-d8a3-40c3-94de-bc23591c9cea">

   var w = [1.2879, 0.5135, 4.9532, -1.502, -1.0922, 0.0081, 1.3771, -0.0294, 0.6718, 1.8335, -0.4066, 0.7291, 0.5517]

**Comment by L-M-Sherlock** [comment]
I recommend not using learning steps longer than one day. Because FSRS doesn't know the intervals used in learning steps. It only know that your first rating is 1. So it gives a short interval. If you insist to use learning steps longer than one day, you should use the FSRS4Anki Helper add-on to reschedule these cards.

**Comment by propofolpapi** [comment]
Ok great, I'll work with this change then. Thank you!
