### ISSUE TITLE
[Question] Explanation for these two options

### ISSUE THREAD

**Issue by BEST8OY** [open-spaced-repetition/fsrs4anki-helper#219]
- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/70865987/85ab6b22-c720-4fdc-8aed-7290409be9b0)

I don't quite understand these two options.

If I activate the first one which card is going to get affected by it? every card which is getting reviewed?

And the second option, I totally don't understand it! aren't siblings already get buried by Anki built-in option! (If possible, explain with an example especially the **sync** part)

I wish there was a better documentation for the helper addon.

**Comment by Expertium** [comment]
Please read this: https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/main/README.md
The first option allows you to slowly and smoothly transition from Anki's default scheduler to FSRS, without rescheduling all cards at once. It also has an upside - you can set learning steps longer than 1d. The downside is that the displayed intervals (above the answer buttons) will no longer match real intervals in that case, but the real ones will be more optimal.
As for the second option - yes, Anki buries siblings, but it only sets them one day apart. FSRS uses a formula that sets them further apart. The longer their intervals, the greater the difference between their dues will be. "After sync" part is exactly what it sounds - you press "Sync", the code runs.

**Comment by user1823** [comment]
@L-M-Sherlock, I agree with the OP that the README doesn't talk about these two options, but it should.

So, I recommend adding description of these two options to the README.

For auto-reschedule after review, use https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/194#issuecomment-1689645951 and https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/194#issuecomment-1693709067.

Add another con: It might have a small (though most likely unnoticeable) effect on power consumption because it needs more number of calculations for each review.

For auto-disperse siblings after sync, mention clearly that it works only for reviews done on other devices.

Also, add description of the auto-reschedule after sync option (even though the name of the option in the menu is clear enough)

**Comment by L-M-Sherlock** [comment]
> Add another con: It might have a small (though most likely unnoticeable) effect on power consumption because it needs more number of calculations for each review.

It also has another con: https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/205#issuecomment-1695133776

It would cause the constant queue rebuilding.

> So, I recommend adding description of these two options to the README.

Where should I insert this description? By the way, PR is welcomed. Today I'm busy integrating FSRS scheduler into Anki.
