### ISSUE TITLE
[BUG ] disperse all the siblings after sync

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/fsrs4anki-helper#272]
This version doesn't seem to disperse all the siblings after sync.

After sync, I got the message "Rescheduled 72 cards. Dispersed 2 siblings in 1 note." (not exactly this, based on memory)

But, I reviewed many cards having siblings. I had expected something like "Dispersed 40 siblings in 20 notes".

_Originally posted by @user1823 in https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/238#issuecomment-1763306849_

**Comment by L-M-Sherlock** [comment]
Could you check whether the 40 siblings are in review stage?

**Comment by user1823** [comment]
The mentioned numbers are all estimates because I don't have the actual numbers.

But, I am sure that the add-on is not dispersing all siblings of the synced reviews.

And yes, I am considering only those cards where both the siblings are in the review stage.

I never faced this issue with the add-on in Anki 2.1.66 but I have started facing this issue since updating to 23.10. So, it seems that this issue is specific to the new version (native FSRS version) of the add-on.

**Comment by user1823** [comment]
> I guess the potential reason is AnkiDroid removed the memory state of these cards.

It seems that you are right.

**Comment by user1823** [comment]
> I think that disabling sibling burying should solve the problem temporarily.

This is working for me.

Also, because there is nothing that you are expected to do to solve this, we can close this issue.

This issue would be solved when the next alpha of AnkiDroid is released.

**Comment by user1823** [comment]
With AnkiDroid 2.17alpha2, this issue has been solved. The dispersal of siblings occurs even after re-enabling sibling burying in Deck Options.
