### ISSUE TITLE
[Question] Is rescheduling using the add-on even necessary anymore?

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki-helper#325]
**Research**

*Enter an [x] character to confirm the points below:*

- [X] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [X] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [X] I have searched for similar existing questions here

**Question**
Since built-in FSRS has it's own rescheduling feature, is "Reschedule all cards" necessary anymore? "Reschedule all cards reviewed in the last n days" is at least somewhat useful, since there is no such feature in Anki, but I can't think of any use-cases for "Reschedule all cards".

**Comment by L-M-Sherlock** [comment]
Maybe it's unused now. I will remove it in the next update.

**Comment by user1823** [comment]
I don't think that there is any need to remove it. Keeping it there is not harmful. The feature can be useful when the user wants to reschedule their cards without adding an extra revlog entry, which otherwise increases the size of the collection.

**Comment by Expertium** [comment]
I just recently had a conversation with a user who was confused by add-on rescheduling vs built-in rescheduling. So I think we should remove it to avoid confusion.

**Comment by L-M-Sherlock** [comment]
The add-on rescheduling is also more convenient than the built-in rescheduling.

**Comment by Expertium** [comment]
I wouldn't say so myself. And personally, I was also initially confused about which option I should use: the built-in one or the add-on one. I think it would be nice to remove it, just to avoid confusing the users.

**Comment by L-M-Sherlock** [comment]
Removed in d2520350ea7fce56652fd3e8e6881153d844051a

**Comment by user1823** [comment]
If this is removed from the main menu & gear options, can you instead add it to the menu in the Browser (the menu in the image below)?
<img width="235" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/80f1cc43-df98-42ba-9b28-52dd8c360330">

I am asking for this because there are certain situations where I want to reschedule only a few cards. Previously, I could move them to another deck and reschedule all cards in that deck. But this is not possible now.

**Comment by Expertium** [comment]
I like your idea, but I think it's better to suggest it to @dae, so that it will be implemented natively to avoid any kind of inconsistency with the fuzz factor.

**Comment by jcznk** [comment]
IMHO, this change is not 100% warranted, at least not yet. 
Helper's reschedule had some features that are missing from native Anki.

Namely:
- it provided the ability to reschedule specific decks instead of the entire collection; 
- you didn't need to adjust FSRS parameters before rescheduling:
- the add-on's rescheduling didn't create a new revlog for each card in the collection, thereby avoiding a non-negligible increase in file size.

Perhaps these features could be better incorporated as native functionalities in Anki. 
However, at present, it seems there is a net loss of functionality.

**Comment by L-M-Sherlock** [comment]
> you didn't need to adjust FSRS parameters before rescheduling;

I think it could be supported easily. @dae, what do you think of that?

**Comment by tkozybski** [comment]
> the add-on's rescheduling didn't create a new revlog for each card in the collection, thereby avoiding a non-negligible increase in file size.

This won't be the case in the upcoming version of Anki, but I agree that easily accessible rescheduling selected decks only was a very convenient feature that I used a lot.

**Comment by DerDemystifier** [comment]
I think it's still necessary for users coming from older version to the new 23.10+ versions with FSRS enabled. They will probably need to reschedule all cards at least once.

From README:
> Note: For cards that have been reviewed multiple times using Anki's default algorithm, **_rescheduling may give different intervals than the Scheduler_** because the **Scheduler can't access the full review history when running**. In this case, the intervals given by rescheduling will be more accurate. But **_after rescheduling once, there will be no difference between the two_**.

**Comment by Expertium** [comment]
Built-in "Reschedule cards on change" will accurately recalculate memory states (DSR values), so no, you don't need the add-on feature if you are switching from standalone FSRS to built-in FSRS in 23.10+.

**Comment by DerDemystifier** [comment]
> if you are switching from standalone FSRS to built-in FSRS in 23.10+.

I meant coming from an older version of Anki using V2 scheduler. Talking from experience, I had to use the Schedule all cards option only once coming to FSRS and noticed that I had many cards that I wouldn't have seen for another year or so brought ahead after rescheduling all cards.

If I hadn't pressed the "Reschedule all cards". I wouldn't have seen those cards (that I have already forgotten) for another year because of the old SM2 algorithm.

I think it's important to reschedule all cards if one's coming to FSRS for the first time. I may be wrong, I'm just saying.

**Comment by user1823** [comment]
> I think it's important to reschedule all cards if one's coming to FSRS for the first time.

Yes, you need to reschedule all cards when starting to use FSRS (if you want a instant transition). But, you can use Anki's built in "Reschedule cards on change" option for that purpose. The current issue is about a similar option in the add-on.

**Comment by DerDemystifier** [comment]
> But, you can use Anki's built in "Reschedule cards on change" option for that purpose.

Ah, I guess you're right. I totally missed that option.

**Comment by aleksejrs** [comment]
> Anki's built in "Reschedule cards on change" option

As far as I remember, that adds some activity when doing something in the FSRS settings. But I can't check it, because I can't enable that option in Anki 23.12 beta 3.

**Comment by aleksejrs** [comment]
Anki's built in "Reschedule cards on change" option is not saved, so you have to click it every time.
If it was saved, it would be annoying when you are just checking if optimization helps.

**Comment by aleksejrs** [comment]
Also maybe the add-on's feature makes it easier to see how the settings change affects due numbers.

**Comment by meliache** [comment]
I just noticed that the button disappeared so checked the issues to find the reason. I used the `Reschedule all cards` button to utilize the helper-addons built-in load balancing. My intuition was that load-balancing mostly moves cards with high stabilities (studied more than 7 days ago) because a couple of days difference in the review date don't matter much for those. As far as I know built-in FSRS has fuzz, but it's different from load-balancing which I imagine takes into account the load of adjacent days. Maybe I misunderstood the feature and for load-balancing I don't need to reschedule via the addon?

**Comment by aleksejrs** [comment]
If you move a card between decks with different presets, the card may need rescheduling even if it hasn't been reviewed recently.

**Comment by L-M-Sherlock** [comment]
Fine. I will revert the change in the next update.

**Comment by L-M-Sherlock** [comment]
Reverted in 247e94e067203f53ccea3e5d0a4dd8446673385c
