### ISSUE TITLE
[Question] Best way to handle rebalancing of a deck with massive amount of cards?

### ISSUE THREAD

**Issue by ratman-codes** [open-spaced-repetition/fsrs4anki-helper#332]
I have a deck with a very high amount of cards (18k). I only have 93 reviews a day right now as its mostly long term matures.

I previously tested load rebalance with another deck with only 2k cards. Because my long term mature rate was so low (60-70%) it put 1500 reviews on day 1. That was fine for that deck.

This deck has much higher long term mature rate, but still -- if something like that happens, it will be utterly disastrous for obvious reasons. I'm wondering if there's a "best practice" for saving my current deck state before I hit load rebalance button. Most likely htiting "undo" won't work so do I need to export my entire deck as a backup first? Or some other better method?

**Comment by ratman-codes** [comment]
OK, sorry to change the direction of this question. I decided to bite the bullet and try this. I exported my deck and synced to anki server before doing it. Upon rescheduling, I got 5500 cards due today. This is really high. For context these cards take me about 10 seconds to review each. That's 55k seconds = 916 minutes = 15 hours of pure reviewing required to get thru this backlog. Any advice from other users with similar large decks that you ended up doing a big reschedule for?

**Comment by Expertium** [comment]
You don't have to reschedule cards. Assuming you are using built-in FSRS, you can just leave "Reschedule cards on change" off. Also, you can use the Postpone feature of the add-on to postpone some cards, and only go through, for example, 500 per day.

**Comment by user1823** [comment]
As Expertium said, you don't need to reschedule all your cards when using built-in FSRS. This will allow you to transition to FSRS gradually, rather than instantly.

However, many users want to transition instantly (because otherwise it may be even several months before Anki shows you a card that you have long forgotten). In that case, the recommended way to deal with a backlog is the following:

In the Deck Options, 
- set the "Review sort order" to "Relative Overdueness",
- set the "Maximum reviews/day" to a high (but manageable) value and
- set "New cards/day" to zero or a very small value.

After you have cleared the backlog, remember to restore these settings to their previous values.

One can also use the `Postpone` function of the add-on, as suggested by Expertium. However, it is not the "ideal" solution as it just sweeps the problem under the rug.

**Comment by L-M-Sherlock** [comment]
This method would be also helpful: https://refold.la/roadmap/stage-1/c/srs-best-practices#Falling-Behind

**Comment by aleksejrs** [comment]
> This method would be also helpful: https://refold.la/roadmap/stage-1/c/srs-best-practices#Falling-Behind

**Relative** Overdueness prioritizes cards with short priorities, too.

Focusing on one language should make reviews faster, although there are pros and cons to it.
