### ISSUE TITLE
[Feature Request] Automatically apply Load Balance

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki-helper#377]
Right now Load Balance only works when rescheduling cards using the add-on. I doubt that many people use the add-on rescheduling, and likely even fewer people do it every day. I propose implementing one or two of the following features:
1) Load Balance when Anki starts
2) Load Balance on Sync
3) Load Balance when Anki is closed

We already have "Auto apply easy days on closing collection", which means that there shouldn't be any technical difficulties. @user1823, I would also like to know your opinion.

**Comment by user1823** [comment]
> Load Balance when Anki starts

This can slow down the launch of Anki. This was the main reason Auto Easy Days is applied on closing the collection, not opening the collection.

> Load Balance on Sync

We don't want to run load balance on every sync. It would be wasteful.

> Load Balance when Anki is closed

This seems to be fine but the rescheduled cards would not be synced. I think that this is also a problem with auto easy days.

If there is a hook for the automated sync that occurs before closing the collection, it may be best to run the auto load balance just before the automated sync.

By the way, I think that the load balance feature is not very useful. It creates an impression that it is making the load more balanced. But actually, it is just continuously moving cards forwards and backwards. So, if you use it once and then never use it again, it makes your workload more unbalanced rather than balanced. See https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/372

**Comment by L-M-Sherlock** [comment]
It's not very useful unless the load balance takes effect immediately after the user presses the rating button.

**Comment by Expertium** [comment]
In it's current implementation it's not very useful either, since most people use built-in rescheduling option and don't use add-on rescheduling.

**Comment by user1823** [comment]
@L-M-Sherlock, if there is a hook for the Congrats page, you can search for `rated:1` and reschedule those cards when the user reaches the Congrats page. This won't cause the queue rebuilding problem.

People who do their reviews on other devices can use the `Reschedule cards reviewed on other devices` option.

**Comment by user1823** [comment]
Damien said the following in https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/205#issuecomment-1695183840:
> If, for now, you want to address this in an add-on instead of the Rust core, a hook could be added to the congrats screen and/or or deck list if there isn't one already.

Also, there is a hook for the Congrats page: https://forums.ankiweb.net/t/help-needed-congratulations-screen-as-a-hook/36158/2

So, I think that the best way is to use the above hook for Auto Load Balance, Auto Easy Days (instead of using opening / closing the collection as the hook) and Auto Disperse (instead of using answering card as the hook).

**Comment by L-M-Sherlock** [comment]
I will do some research about that hook in this week.

**Comment by user1823** [comment]
Later, I realised that there are two problems with this approach:
- Let's say the user does a few reviews on Desktop and then completes the reviews on the phone. In this case, the user won't reach the Congrats page on the Desktop. So, the reviews done on the Desktop won't be rescheduled/ dispersed.
- Let's say a user does some reviews one day but doen't complete the reviews. He then completes the reviews the next day. Since we are searching for `rated:1`, we won't be able to reschedule/ disperse the reviews performed on the previous day.

**Comment by L-M-Sherlock** [comment]
Yeah. Maybe we just need to wait until dae integrates load balance into Anki?

**Comment by L-M-Sherlock** [comment]
The helper add-on won't support this feature. Please wait for the integration.
- https://github.com/ankitects/anki/issues/3116
