### ISSUE TITLE
[BUG] It seems like Load Balancing makes today "easy" even without Easy Days

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/fsrs4anki-helper#386]
Sometimes I "Optimize all presets" and don't reschedule all the cards. Does applying Easy Days reschedule the dues to when they would be if I rescheduled all cards?

But it seems like Load Balancing makes today "easy" even without Easy Days (I did only 4 reviews).

### without Load Balancing (680 cards backlog):
![Screenshot_2024-04-09_12-34-21](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/1025861/7a0e09b0-91b6-4d55-91ce-de1cbdd1e9f1)
### with Load Balancing, without Easy Days (19 cards backlog, today's Due decreased so much for no reason):
![Screenshot_2024-04-09_12-40-43 load bal, no easy days](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/1025861/60caba2b-f4d2-49a6-abb8-268990eb3b57)
### with Load Balancing, Easy Days Thursday-Sunday (22 cards backlog):
![Screenshot_2024-04-09_12-46-10 loadbal, easy Thu-Sun](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/1025861/486dcc56-e346-4ec2-a2c7-ab918b449b9c)

_Originally posted by @aleksejrs in https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/384#issuecomment-2044527998_

**Comment by aleksejrs** [comment]
I am not sure I can get to this within a month, or that I should, considering #409 and the below. I have hundreds of decks and tens of note types and it was hard and daunting to clean that up.

I haven't been using Load Balancing since then. Instead, I just used Advance a few times.
Now I don't have to adjust Easy Days based on how I feel. The fluctuations of load are not comparable to the fluctuations of my ability to review.
If a backlog appears, I just prefer the easier or more important cards and do not worry that I will have to review many difficult unimportant cards.
It is easier to think about [limits](https://github.com/lune-stone/anki-addon-limit-new-by-young) without Easy Days.

**Comment by L-M-Sherlock** [comment]
Fine. Could I close this issue? I haven't seen another user reports this bug. Maybe it has been solved.

**Comment by aleksejrs** [comment]
Yes, please.
