### ISSUE TITLE
[Feature Request] Rework Advance and Postpone

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki-helper#406]
**Is your feature request related to a problem? Please describe.**
Originally, back these features were just introduced, I thought they worked like this:
1) Get R and desired retention
2) Calculate the difference between desired retention and R **after** advancing/postponing
3) Advance/postpone based on that difference

The key point is that we're not comparing desired retention to the current R, before the changes. We are comparing it to R after the changes. For example, if the card is about to be postponed by 1 day, we do not compare R(today) with desired retention, we compare R(today+1) with desired retention. But recently I looked at the code and found that that's not how these things work.

**Describe the solution you'd like**
The method I described above is better than the current implementation. Suppose that we have 2 cards, both with R=90%, and desired retention is 90%. It appears that postponing either of them would have the same effect. However, they have different values of S, and as a result, postponing card 1 would reduce R from 90% to 89%, and postponing card 2 would reduce R from 90% to 80%. The latter produces a larger deviation from optimal scheduling, and hence the first card should be postponed.

**Comment by user1823** [comment]
Firstly, advance is not affected by this issue. In that case, we are actually interested in the retention of the card today because the card is going to become due today.

Now, let's talk about postpone.

> They have different values of S, and as a result, postponing card 1 would reduce R from 90% to 89%, and postponing card 2 would reduce R from 90% to 80%. 

As you can see in the following code, if the R is the same, the card with longer interval is postponed first. So, at a quick glance, the add-on seems to be doing what you have proposed.

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/fd2ac3e204f62ddc9bd28543423d95682edd96f0/schedule/postpone.py#L73-L74

However, there is a catch.

With the current approach, a card would be postponed from 90% to 80% before another card is postponed from 88% to 86%. If we follow your idea and sort the cards based on their R after postponing, this issue will be solved.

**Comment by user1823** [comment]
I have created a PR: https://github.com/open-spaced-repetition/fsrs4anki-helper/pull/407

**Comment by Expertium** [comment]
> Firstly, advance is not affected by this issue. In that case, we are actually interested in the retention of the card today because the card is going to become due today.

Fair point.
