### ISSUE TITLE
[Feature Request] Auto-rescheduling should only occur when changes are synced from AnkiWeb to Anki Desktop (i.e. a download) and not when changes are uploaded to AnkiWeb.

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/fsrs4anki-helper#46]
> I think that the rescheduling should only occur when changes are synced from AnkiWeb to Anki Desktop (i.e. a download) and not when changes are uploaded to AnkiWeb.

I don't know how to implement it. Maybe someone could help me. I will open a new issue.

_最初由 @L-M-Sherlock 在 https://github.com/open-spaced-repetition/fsrs4anki/issues/156#issuecomment-1464280530 发布_

**Comment by user1823** [comment]
I think that in the following code, the Straight Rewards add-on filters the cards whose intervals have changed after sync.

https://github.com/hgiesel/anki_straight_reward/blob/master/src/lib/sync_hook.py

So, possibly, we can also use this for filtering such cards and apply rescheduling to those cards (instead of using the reschedule recently reviewed cards function).

But, after we get the list of those cards, we would need to exclude the learning cards and the suspended cards (as the helper currently does).

By the way, why does the helper not reschedule buried cards? This change was introduced in https://github.com/open-spaced-repetition/fsrs4anki-helper/pull/44.

**Comment by L-M-Sherlock** [comment]
> By the way, why does the helper not reschedule buried cards? This change was introduced in #44.

If the helper reschedules the buried cards, should it unbury them? I don't know how to deal with it. And the due of buried cards is not the actual due date. Not rescheduling buried cards is safe.

**Comment by L-M-Sherlock** [comment]
> I think that in the following code, the Straight Rewards add-on filters the cards whose intervals have changed after sync.

Thanks for your valuable information. I will read the code. By the way, the current rescheduling is faster than before. Is it still very helpful to filter cards before rescheduling?

**Comment by user1823** [comment]
> By the way, the current rescheduling is faster than before. Is it still very helpful to filter cards before rescheduling?

Yes, it is still helpful to filter the cards before rescheduling.

The first reason is that filtering the cards before rescheduling prevents the wastage of network resources. Otherwise, the changed due dates and intervals for all the cards would need to be synced even if there was a need to reschedule only few of the cards.

The second reason (and more practical one) is that there is still a difference in the time required to reschedule recently reviewed cards and to reschedule all cards.

For me,
- rescheduling recently reviewed cards takes 2-3 seconds.
- rescheduling all cards takes 10-15 seconds.

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11242262/fsrs4anki-helper.zip)
Commit: https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/579e46a73fa19032a47c0df551abefc2fc80bb5c

**Comment by user1823** [comment]
This works as intended. Thanks.
