### ISSUE TITLE
[Feature Request] return to state before all rescheduling

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/fsrs4anki-helper#54]
I'd like to go back to Anki's v2 scheduler, but even after setting that preference in Anki, I still have all the cards with unrealistically long intervals. How can I get their intervals back down to v2 scheduler values?

_Originally posted by @mantixero in https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/49#issuecomment-1499445519_

**Comment by user1823** [comment]
I wanted to clarify an important point.

I think that the users would not want to revert to the state before the rescheduling. Rather, they would want to reschedule their cards to the interval the Anki scheduler would have provided.

So, we would need to calculate the interval between the last two reviews and then use the default Anki formulas (based on the rating) to calculate the new interval.

**Comment by L-M-Sherlock** [comment]
> So, we would need to calculate the interval between the last two reviews and then use the default Anki formulas (based on the rating) to calculate the new interval.

It would not be too complex like this. I will just set the interval and due of cards with the `ivl` and `due` in the last revlog.

**Comment by L-M-Sherlock** [comment]
[fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11175990/fsrs4anki-helper.zip)

@mantixero I developed a patch. Could you give it a try?

**Comment by user1823** [comment]
> I will just set the interval and due of cards with the `ivl` and `due` in the last revlog.

I have not tested it practically. But, wouldn't the `ivl` and `due` in the last revlog be those which were calculated by FSRS, rather than those which Anki would have assigned?

**Comment by L-M-Sherlock** [comment]
> I have not tested it practically. But, wouldn't the `ivl` and `due` in the last revlog be those which were calculated by FSRS, rather than those which Anki would have assigned?

The rescheduling would not modify the revlog.

**Comment by user1823** [comment]
What if the last review was done on Anki Desktop with the FSRS scheduler enabled?

**Comment by L-M-Sherlock** [comment]
> What if the last review was done on Anki Desktop with the FSRS scheduler enabled?

Resetting would not affect this case.

**Comment by user1823** [comment]
But, I think that this case should also be dealt with. 

What do you think, @mantixero?

**Comment by mantixero** [comment]
> I think that the users would not want to revert to the state before the rescheduling. Rather, they would want to reschedule their cards to the interval the Anki scheduler would have provided.

user1823 is correct: I would like the intervals to be whatever the v2 scheduler would have made them if I had done my reviews under that scheduler, and not only my last review of each card, but all reviews done under the FSRS scheduler (everything since Dec. 16, 2022 in my case), taking into account Anki's interval modifier value, which in my case is 0.82, which I think means that intervals are only 82% as long as Anki would normally assign them.

FSRS will need to record when it began taking over the scheduler, and for every review performed since that date, retroactively modify the intervals Anki would have assigned, or at least calculate the latest interval in steps of the v2 scheduler. For example, here's a card I studied under the v2 scheduler:

![Screenshot 2023-04-07 Ankiv2](https://user-images.githubusercontent.com/38519777/230617773-bae94ef4-55c6-4cb7-858b-130c42465260.png)

After the 1 day interval, it continues to 3 days, 6 days, 14 days, and so on. However, comparing that to a card studied under the FSRS scheduler:

 
![Screenshot 2023-04-07 FSRS](https://user-images.githubusercontent.com/38519777/230618141-4096dc40-025e-4d18-b2ec-1e77c9a74c3f.png)

After passing this card after an 8-day interval under FSRS at a requested retention rate of 0.93, it's now not scheduled to come back for 4.47 months. Not only should that 8-day interval be recalculated as if it were a shorter interval (perhaps we could count it as the 6-day interval Anki would have given it, skipping the 3-day interval that obviously wasn't necessary since I remembered the information for 8 days), but the current interval should be something like 14 days.

Here you can see where I held out hope for FSRS: I obviously don't need all the repetitions at the young card stage like the 3-day intervals, and I might have even remembered the information for 14 days instead of 8, but jumping from an 8-day interval to 4.47 months after only a couple of reviews just seems unrealistic, and the intervals only grow more unrealistic from there. This is why, even though I don't enjoy the unnecessary reviews for young cards under Anki's v2 scheduler, that I'd rather keep using it over FSRS since I know its mature intervals result in a retention rate I'm happy with (93%).

**Comment by L-M-Sherlock** [comment]
Could you give the patch a try? It would solve most problems caused by rescheduling. The FSRS scheduler is conservative in the existing cards. So it may not cause serious problem.

**Comment by mantixero** [comment]
To use it after installing the zip, I just click FSRS4Anki Helper > Reschedule all cards, correct?

**Comment by L-M-Sherlock** [comment]
I add a new button named `reset all cards`.

**Comment by user1823** [comment]
Though there is nothing wrong in trying, I think that this patch won't be much helpful.

I am saying this because it seems to me that @mantixero last rescheduled their cards in December and is using the FSRS scheduler since then. So, the revlogs contain the ivl and due date calculated by the FSRS scheduler and not those calculated by Anki.

> The FSRS scheduler is conservative in the existing cards. So it may not cause serious problem.

I think that this would not be the case if the user rescheduled their cards using the helper before using the FSRS scheduler.

**Comment by L-M-Sherlock** [comment]
> Though there is nothing wrong in trying, I think that this patch won't be much helpful.

In worst, it could only reset those cards of which intervals are unrealistic long. These cards would not be reviewed view FSRS.

**Comment by user1823** [comment]
@L-M-Sherlock
So, my (and your) predictions came out to be true.

Now, to correct the intervals of the few cards that still have inappropriate intervals, we would have to use something similar to what I proposed initially. I am mentioning that solution here again:
> We would need to calculate the interval between the last two reviews and then use the default Anki formulas (based on the rating) to calculate the new interval.

Probably, instead of applying this to all the cards, the helper should apply this to only those cards which were not reset by the approach used currently (reading due and ivl from revlogs). 

Also, to avoid confusion, I suggest that the name of the new option should be changed from "Reset all cards" to "Revert to Anki scheduler".

**Comment by L-M-Sherlock** [comment]
> We would need to calculate the interval between the last two reviews and then use the default Anki formulas (based on the rating) to calculate the new interval

I recommend resetting these cards manually. The case in this issue is seldom seen. To implement a complex feature for it is inefficient, and could induce more problems.

**Comment by mantixero** [comment]
How do I reset the cards manually, and what exactly will that do? I don't want to send them back to the Learning state.

**Comment by L-M-Sherlock** [comment]
> How do I reset the cards manually, and what exactly will that do?

![image](https://user-images.githubusercontent.com/32575846/230705972-78b9ee35-8630-4fc6-91ae-a860a0962a11.png)
![image](https://user-images.githubusercontent.com/32575846/230706018-e84c5114-afca-4e8c-942b-51647e7d1011.png)

**Comment by user1823** [comment]
@L-M-Sherlock
I think that the PR linked to this issue should be merged now after making the following change:

> To avoid confusion, I suggest that the name of the new option should be changed from "Reset all cards" to "Revert to Anki scheduler".

**Comment by L-M-Sherlock** [comment]
But it doesn't revert to Anki built-in schedule. That name could be confusing.

**Comment by L-M-Sherlock** [comment]
But it doesn't revert to Anki built-in schedule. That name could be confusing.

**Comment by user1823** [comment]
Ok, then name it: "Undo Rescheduling"
