### ISSUE TITLE
[Feature Request] Don't ask user before auto-dispersing when user store the choice in the config file

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/fsrs4anki-helper#76]
It works fine after this patch. Thanks!

But, I want to share the following points:
- Currently, the helper requests the user to approve dispersing the cards after every sync. Doesn't it make sense to store the user's choice in the config file?
- If we indeed store the user's preference in the config file and remove the askUser function, the two tooltips (reschedule + disperse_siblings) would be scheduled to come one after the other. This would cause the reschedule tooltip to be not shown at all because the disperse_siblings tooltip will close the reschedule one. So, we might want to save the contents of the reschedule tooltip and display it along with the disperse_siblings tooltip.

_Originally posted by @user1823 in https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/67#issuecomment-1513247003_

**Comment by szalejot** [comment]
I came to this section to post this Feature Request but it's already posted.
So +1 from my side.

**Comment by user1823** [comment]
With the latest update, this issue has been solved. But, the behavior is not exactly what is expected.

Now, if no cards are rescheduled (e.g. if no reviews were done on other devices), the helper doesn't show the tooltip saying "0 cards rescheduled." This raises a concern about whether the function was executed or not. So, I think that in this case, it should show a tooltip saying "0 cards rescheduled." (just like it did before the last update).

Similarly, I think that disperse_siblings should also show such tooltip, saying "0 siblings dispersed" if there were no siblings to disperse.

However, the disperse_siblings tooltip message should not appear if there were no cards to reschedule in the first place. This is because a message like the following seems odd.
"0 cards rescheduled. 0 siblings dispersed."

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11711843/fsrs4anki-helper.zip)
Commit: https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/233dae3b722b30bb8796f67ffd6f3812e713d478

Could you test this version? I think it satisfies your requirements.
